name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Compile contracts
        run: yarn compile
      - name: Store contract artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts-artifacts
          path: build
      - name: Create .env with Github Secrets
        run: |
          touch .env
          echo FORK_RPC_PROVIDER=$FORK_RPC_PROVIDER >> .env
          echo USDC_OWNER_ADDRESS=$USDC_OWNER_ADDRESS >> .env
        env:
          FORK_RPC_PROVIDER: ${{ secrets.FORK_RPC_PROVIDER }}
          USDC_OWNER_ADDRESS: ${{ vars.USDC_OWNER_ADDRESS }}
      - name: Hardhat Tests
        run: |
          yarn test

